### ISSUE TITLE
Tạo phản hồi , ý kiến cho page bằng Zoho Survey , Zoho Form

### ISSUE THREAD

**Issue by admin2811** [admin2811/MIS#19]

**Comment by NguyenVanNam081203** [comment]
Báo cáo Form Zoho Form - Giải quyết Khiếu nại ; Zoho Survey - Đánh giá chất lượng 
![Image](https://github.com/user-attachments/assets/472459f8-1585-4454-b3fd-464ebb5b7a61)
![Image](https://github.com/user-attachments/assets/c649501b-ada3-4e56-b767-481f7411f12e)
![Image](https://github.com/user-attachments/assets/fe50d435-9b55-4b2a-bb5f-7eb162a2cd4a)
![Image](https://github.com/user-attachments/assets/ecd7cc77-3d33-40d8-961a-b4204bea8487)
![Image](https://github.com/user-attachments/assets/5b2c8b93-1f60-4490-994a-f0f09ae01ddb)
![Image](https://github.com/user-attachments/assets/e68ec8f3-ea22-410f-9a25-ca86fe94f527)
![Image](https://github.com/user-attachments/assets/754ac54b-c54f-4d80-b718-f3e52e6a2c61)
