### ISSUE TITLE
Đăng tin tuyển dụng cho website, trả về số lượng người khi thực hiện điền form đăng ký cho vị trí công việc

### ISSUE THREAD

**Issue by admin2811** [admin2811/MIS#29]

**Comment by NguyenVanNam081203** [comment]
![Image](https://github.com/user-attachments/assets/f0417bf5-775f-47e9-a404-ca8d405539d5)
![Image](https://github.com/user-attachments/assets/fc99787d-0f9a-49bb-8b09-964e8942147b)
![Image](https://github.com/user-attachments/assets/aed8b566-6b0a-4a95-944f-f61a62cc3bcb)
![Image](https://github.com/user-attachments/assets/04a80689-e1a0-457d-89cf-49cc43878a40)
![Image](https://github.com/user-attachments/assets/a2449548-b09c-4300-a751-babb00997424)

**Comment by NguyenVanNam081203** [comment]
![Image](https://github.com/user-attachments/assets/d599fc85-f462-4e77-a921-48676d9f9145)
check số lượng
