### ISSUE TITLE
Tìm hiểu , tạo kênh tik tok cho cửa hàng

### ISSUE THREAD

**Issue by admin2811** [admin2811/MIS#7]
Hoàn thiện trong tối nay

**Comment by NguyenVanNam081203** [comment]
TikTok shop: https://seller-vn.tiktok.com/profile/seller-profile?tab=seller_information_old
![Image](https://github.com/user-attachments/assets/a1ebd4c0-ce3e-4d0b-9a6c-06ebbc86a6fa)
